// bot/src/commands/stats.ts
import { SlashCommandBuilder, ChatInputCommandInteraction, EmbedBuilder } from 'discord.js';
import { IBotCommand } from '../core/types.js';
import { BotContext } from '../core/BotContext.js';
import { ApiError } from '../core/ApiClient.js';
import { createRenakoGeneralErrorEmbed } from '../utils/embedGenerator.js';

export class StatsCommand implements IBotCommand {
    data = new SlashCommandBuilder()
        .setName('stats')
        .setDescription('View your Catan career (if Renako doesn\'t collapse first)');
    aliases = ['s'];

    async execute(interaction: ChatInputCommandInteraction, { api }: BotContext): Promise<void> {
        await interaction.deferReply();

        try {
            const stats = await api.getStats(interaction.user.id);

            // Handle "User exists in DB but has 0 games"
            if (!stats || Number(stats.total_games) === 0) {
                const emptyEmbed = new EmbedBuilder()
                    .setTitle('🌸 E-eh?! Your stats are... empty?!')
                    .setDescription(
                        "*R-Renako frantically checks her notes...*\n\n" +
                        "Oh! You haven't played any tracked games yet! " +
                        "That's totally okay! I mean, I get nervous playing too... " +
                        "especially when people are watching... (⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)"
                    )
                    .addFields({ 
                        name: '💕 How to get started (I-I think!)', 
                        value: 
                            '```md\n' +
                            '1. Use /link to connect your account\n' +
                            '2. Install the browser extension\n' +
                            '3. Play a game on Colonist.io\n' +
                            '4. Come back and I\'ll show you stats!\n' +
                            '   (Please don\'t be mad if it breaks...)\n' +
                            '```',
                        inline: false
                    })
                    .setColor('#FFB6C1')
                    .setFooter({ 
                        text: '💭 Renako\'s Social Battery: [■■□□□] (Barely hanging on...)',
                        iconURL: interaction.user.displayAvatarURL()
                    })
                    .setTimestamp();

                await interaction.editReply({ embeds: [emptyEmbed] });
                return;
            }

            // Calculate some Renako-style commentary
            const winRate = parseFloat(stats.win_rate);
            let renakoComment = '';
            let renakoMood = '';
            
            if (winRate >= 50) {
                renakoComment = "W-wow! You're really good! Unlike me who panics every turn... (´,,•ω•,,)";
                renakoMood = '✨ Impressed (but also intimidated)';
            } else if (winRate >= 30) {
                renakoComment = "Those are solid stats! Better than mine probably... I-I mean, not that I play much!";
                renakoMood = '🌸 Encouraging (in her own way)';
            } else {
                renakoComment = "H-hey, don't worry! We all have rough games... I lose at life daily! (╥﹏╥)";
                renakoMood = '💕 Sympathetically panicking';
            }

            const embed = new EmbedBuilder()
                .setAuthor({ 
                    name: '📊 CatanStats Report Card',
                    iconURL: interaction.user.displayAvatarURL()
                })
                .setTitle(`✨ ${interaction.user.username}'s Stats ✨`)
                .setColor('#FFB6C1')
                .setThumbnail(interaction.user.displayAvatarURL())
                .addFields(
                    { 
                        name: '🎮 Total Games', 
                        value: `\`\`\`yaml\n${stats.total_games} games\n\`\`\``, 
                        inline: true 
                    },
                    { 
                        name: '🏆 Wins', 
                        value: `\`\`\`yaml\n${stats.wins} victories\n\`\`\``, 
                        inline: true 
                    },
                    { 
                        name: '📈 Win Rate', 
                        value: `\`\`\`yaml\n${stats.win_rate}%\n\`\`\``, 
                        inline: true 
                    },
                    { 
                        name: '⭐ Average Victory Points', 
                        value: `\`\`\`fix\n${stats.avg_vp} VP per game\n\`\`\``, 
                        inline: false 
                    }
                )
                .setFooter({ 
                    text: '🌸 Generated by Amori Renako | Social Battery: [■□□□□] (Send help)',
                    iconURL: interaction.user.displayAvatarURL()
                })
                .setTimestamp();

            await interaction.editReply({ embeds: [embed] });

        } catch (error) {
            if (error instanceof ApiError && (error.kind === 'rate_limit' || error.kind === 'upstream')) {
                await interaction.editReply({ embeds: [createRenakoGeneralErrorEmbed()] });
                return;
            }
            // Renako panic mode!
            const panicEmbed = new EmbedBuilder()
                .setTitle('💦 A-AHHH! Something went wrong!')
                .setDescription(
                    "```\n" +
                    "ERROR: Renako is having a breakdown!\n" +
                    "Status: [PANICKING]\n" +
                    "```\n\n" +
                    "*Renako is frantically flipping through her notes...*\n\n" +
                    "I-I can't find your account in the database! (╥﹏╥)\n\n" +
                    "Did you forget to use `/link`? Or maybe the database is broken? " +
                    "Or maybe *I'm* broken?! No no, stay calm Renako... " +
                    "deep breaths... one, two...\n\n" +
                    "```fix\n" +
                    "Please try:\n" +
                    "→ Using /link to connect your account\n" +
                    "→ Waiting a moment and trying again\n" +
                    "→ Not judging me too harshly... (⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)\n" +
                    "```"
                )
                .setColor('#FF69B4')
                .setFooter({ 
                    text: '💔 Renako\'s Social Battery: [DEPLETED] (I need a nap...)',
                })
                .setTimestamp();

            await interaction.editReply({ embeds: [panicEmbed] });
        }
    }
}